apiVersion: v1
kind: ServiceAccount
metadata:
  name: asteroid-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: asteroid-role
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: asteroid-role-binding
subjects:
- kind: ServiceAccount
  name: asteroid-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: asteroid-role
  apiGroup: rbac.authorization.k8s.io