apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: asteroid-test
spec:
  serviceName: asteroid-axum-server-example
  replicas: 3
  selector:
    matchLabels:
      app: asteroid-axum-server-example
  template:
    metadata:
      labels:
        app: asteroid-axum-server-example
    spec:
      serviceAccountName: asteroid-sa
      containers:
        - name: asteroid
          image: asteroid-axum-server-example:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
            - containerPort: 9559
          env:
            - name: SVC
              value: "asteroid-axum-server-example"
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: asteroid-axum-server-example
spec:
  clusterIP: None
  selector:
    app: asteroid-axum-server-example
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: mq
      port: 9559
      targetPort: 9559
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: asteroid-role-binding
subjects:
  - kind: ServiceAccount
    name: asteroid-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: asteroid-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: asteroid-network-policy
spec:
  podSelector:
    matchLabels:
      app: asteroid-axum-server-example
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: asteroid-axum-server-example
      ports:
        - port: 9559
        - port: 8080
  egress:
    # 允许 DNS 查询
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # 允许访问其他 Pod
    - to:
        - podSelector:
            matchLabels:
              app: asteroid-axum-server-example
      ports:
        - port: 9559
        - port: 8080
