/*
 Generated by typeshare 1.11.0
*/


export type EndpointAddr = string;

/**
 * # Interest
 * ## Glob Match Interest
 * (/)?(<path>|<*>|<**>)/*
 */
export type Interest = string;

export type MessageId = string;

export type Subject = string;

/** code are expect to be a valid utf8 string */
export type TopicCode = Uint8Array;

export enum EdgeErrorKind {
	Decode = "Decode",
	TopicNotFound = "TopicNotFound",
	Internal = "Internal",
}

export interface EdgeError {
	context: string;
	message?: string;
	kind: EdgeErrorKind;
}

export enum MessageAckExpectKind {
	Sent = "Sent",
	Received = "Received",
	Processed = "Processed",
}

export enum MessageTargetKind {
	Durable = "Durable",
	Online = "Online",
	Available = "Available",
	Push = "Push",
}

export interface MessageDurabilityConfig {
	expire: Date;
	max_receiver?: number;
}

export interface EdgeMessageHeader {
	ack_kind: MessageAckExpectKind;
	target_kind: MessageTargetKind;
	durability?: MessageDurabilityConfig;
	subjects: Subject[];
	topic: TopicCode;
}

export interface EdgeMessage {
	header: EdgeMessageHeader;
	payload: Uint8Array;
}

export type EdgeRequestEnum = 
	| { kind: "SendMessage", content: EdgeMessage };

export interface EdgeRequest {
	seq_id: number;
	request: EdgeRequestEnum;
}

export type EdgeResult<T, E> = 
	| { kind: "Ok", content: T }
	| { kind: "Err", content: E };

export type EdgeResponseEnum = 
	| { kind: "SendMessage", content: EdgeResult<WaitAckSuccess, WaitAckError> };

export interface EdgeResponse {
	seq_id: number;
	result: EdgeResult<EdgeResponseEnum, EdgeError>;
}

export interface MessageHeader {
	message_id: MessageId;
	ack_kind: MessageAckExpectKind;
	target_kind: MessageTargetKind;
	durability?: MessageDurabilityConfig;
	subjects: Subject[];
}

export interface Message {
	header: MessageHeader;
	payload: Uint8Array;
}

export enum MessageStatusKind {
	Sending = "Sending",
	Unsent = "Unsent",
	Sent = "Sent",
	Received = "Received",
	Processed = "Processed",
	Failed = "Failed",
	Unreachable = "Unreachable",
}

export enum WaitAckErrorException {
	MessageDropped = "MessageDropped",
	Overflow = "Overflow",
	NoAvailableTarget = "NoAvailableTarget",
}

export interface WaitAckError {
	status: Record<EndpointAddr, MessageStatusKind>;
	exception?: WaitAckErrorException;
}

export interface WaitAckSuccess {
	status: Record<EndpointAddr, MessageStatusKind>;
}

export type EdgePayload = 
	| { kind: "Push", content: EdgePush }
	| { kind: "Response", content: EdgeResponse }
	| { kind: "Request", content: EdgeRequest }
	| { kind: "Error", content: EdgeError };

export type EdgePush = 
	| { kind: "Message", content: Message };

