apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"asteroid-test","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"asteroid-axum-server-example"}},"template":{"metadata":{"labels":{"app":"asteroid-axum-server-example"}},"spec":{"containers":[{"env":[{"name":"SVC","value":"asteroid-axum-server-example"},{"name":"POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.uid"}}}],"image":"asteroid-axum-server-example:latest","imagePullPolicy":"Never","name":"asteroid","ports":[{"containerPort":8080},{"containerPort":9559}]}],"serviceAccountName":"asteroid-sa"}}}}
  creationTimestamp: "2024-12-28T07:36:42Z"
  generation: 16
  name: asteroid-test
  namespace: default
  resourceVersion: "21408"
  uid: 8bab56f3-e81c-4b01-ba63-d55babd8326c
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: asteroid-axum-server-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-12-28T16:15:20+08:00"
      creationTimestamp: null
      labels:
        app: asteroid-axum-server-example
    spec:
      containers:
      - env:
        - name: SVC
          value: asteroid-axum-server-example
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        image: asteroid-axum-server-example:latest
        imagePullPolicy: Never
        name: asteroid
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9559
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: asteroid-sa
      serviceAccountName: asteroid-sa
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-12-28T07:36:42Z"
    lastUpdateTime: "2024-12-28T08:15:23Z"
    message: ReplicaSet "asteroid-test-5d8459c658" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-28T09:55:35Z"
    lastUpdateTime: "2024-12-28T09:55:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
