apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"asteroid-test","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"asteroid-axum-server-example"}},"serviceName":"asteroid-axum-server-example","template":{"metadata":{"labels":{"app":"asteroid-axum-server-example"}},"spec":{"containers":[{"env":[{"name":"SVC","value":"asteroid-axum-server-example"},{"name":"POD_UID","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"asteroid-axum-server-example:latest","imagePullPolicy":"Never","name":"asteroid","ports":[{"containerPort":8080},{"containerPort":9559}]}],"serviceAccountName":"asteroid-sa"}}}}
  creationTimestamp: "2025-02-21T07:05:31Z"
  generation: 4
  name: asteroid-test
  namespace: default
  resourceVersion: "1202"
  uid: 87d2d344-514e-4d73-847e-77b27f875926
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: asteroid-axum-server-example
  serviceName: asteroid-axum-server-example
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-02-21T15:11:19+08:00"
      creationTimestamp: null
      labels:
        app: asteroid-axum-server-example
    spec:
      containers:
      - env:
        - name: SVC
          value: asteroid-axum-server-example
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: asteroid-axum-server-example:latest
        imagePullPolicy: Never
        name: asteroid
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 9559
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: asteroid-sa
      serviceAccountName: asteroid-sa
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 3
  collisionCount: 0
  currentReplicas: 3
  currentRevision: asteroid-test-54dcd9c9b8
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updateRevision: asteroid-test-54dcd9c9b8
  updatedReplicas: 3
